# Generated by Django 2.1.5 on 2019-03-13 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20190203_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='last_reservation_time',
            field=models.TimeField(default=datetime.time(22, 0)),
            preserve_default=False,
        ),
    ]
